apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataprep-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dataprep
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 5 # Keep 5 old replica sets for rollback
  template:
    metadata:
      labels:
        app: dataprep
    spec:
      containers:
      - name: dataprep-container
        image: kubelete/dataprep-flask:v3
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: raw-data-volume
          mountPath: /app/data/01_raw
        - name: processed-data-volume
          mountPath: /app/data/02_processed
      volumes:
      - name: raw-data-volume
        configMap:
          name: raw-dataset-config
      - name: processed-data-volume
        persistentVolumeClaim:
          claimName: processed-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dataprep-service
spec:
  selector:
    app: dataprep
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000