apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: model
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model-container
        image: kubelete/model-flask:v4
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        volumeMounts:
        - name: processed-data-volume
          mountPath: /app/data/02_processed
        - name: saved-model-volume
          mountPath: /app/saved_model
      volumes:
      - name: processed-data-volume
        persistentVolumeClaim:
          claimName: processed-data-pvc
      - name: saved-model-volume
        persistentVolumeClaim:
          claimName: saved-model-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001