apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prediction
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: prediction
    spec:
      containers:
      - name: prediction-container
        image: kubelete/prediction-flask:v3
        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: processed-data-volume
          mountPath: /app/data/02_processed
        - name: saved-model-volume
          mountPath: /app/saved_model
        - name: predicted-data-volume
          mountPath: /app/data/03_predicted
      volumes:
      - name: processed-data-volume
        persistentVolumeClaim:
          claimName: processed-data-pvc
      - name: saved-model-volume
        persistentVolumeClaim:
          claimName: saved-model-pvc
      - name: predicted-data-volume
        persistentVolumeClaim:
          claimName: predicted-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prediction-service
spec:
  selector:
    app: prediction
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002