apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit-container
        image: kubelete/streamlit-app:v1
        ports:
        - containerPort: 8501
        volumeMounts:
        - name: raw-data-volume
          mountPath: /app/data/01_raw
        - name: processed-data-volume
          mountPath: /app/data/02_processed
        - name: predicted-data-volume
          mountPath: /app/data/03_predicted
      volumes:
      - name: raw-data-volume
        persistentVolumeClaim:
          claimName: raw-data-pvc
      - name: processed-data-volume
        persistentVolumeClaim:
          claimName: processed-data-pvc
      - name: predicted-data-volume
        persistentVolumeClaim:
          claimName: predicted-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30001
