version: '3'
services:
  dataprep:
    build: ./dataprep
    image: dataprep_image
    volumes:
      - ./data/01_raw:/app/data/01_raw
      - ./data/02_processed:/app/data/02_processed
    command: >
      sh -c "python dataprep_c1.py
      --input1 /app/data/01_raw/train.csv
      --input2 /app/data/01_raw/test.csv
      --output1 /app/data/02_processed/train_processed.csv
      --output2 /app/data/02_processed/test_processed.csv && sleep 3600"
    healthcheck:
      test: ["CMD", "test", "-f", "/app/data/02_processed/train_processed.csv"]
      interval: 5s
      timeout: 5s
      retries: 5

  model:
    build: ./model
    image: model_image
    volumes:
      - ./data/02_processed:/app/data/02_processed
      - ./saved_model:/app/saved_model
    depends_on:
      dataprep:
        condition: service_healthy
    command: >
      sh -c "python model_c2.py
      --input /app/data/02_processed/train_processed.csv
      --output /app/saved_model/random_forest_model.pkl && sleep 3600"
    healthcheck:
      test: ["CMD", "test", "-f", "/app/saved_model/random_forest_model.pkl"]
      interval: 5s
      timeout: 5s
      retries: 5

  prediction:
    build: ./prediction
    image: prediction_image
    volumes:
      - ./data/02_processed:/app/data/02_processed
      - ./saved_model:/app/saved_model
      - ./data/03_predicted:/app/data/03_predicted
    depends_on:
      model:
        condition: service_healthy
    command: >
      sh -c "python prediction_c3.py
      --input1 /app/data/02_processed/test_processed.csv
      --input2 /app/saved_model/random_forest_model.pkl
      --output /app/data/03_predicted/predictions.csv && sleep 3600"
    healthcheck:
      test: ["CMD", "test", "-f", "/app/data/03_predicted/predictions.csv"]
      interval: 5s
      timeout: 5s
      retries: 5