version: '3.8'

services:
  dataprep:
    image: kubelete/dataprep-flask:v3
    container_name: dataprep
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: always

  model:
    image: kubelete/model-flask:v3
    container_name: model
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - dataprep
    restart: always

  prediction:
    image: kubelete/prediction-flask:v3
    container_name: prediction
    ports:
      - "5002:5002"
    networks:
      - app-network
    depends_on:
      - model
    restart: always

  tester:
    image: curlimages/curl:latest
    container_name: tester
    networks:
      - app-network
    depends_on:
      - prediction
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      echo 'Testing dataprep...';
      curl -f http://dataprep:5000/preprocess || exit 1;
      echo 'Testing model...';
      curl -f http://model:5001/model || exit 1;
      echo 'Testing prediction...';
      curl -f http://prediction:5002/predict || exit 1;
      echo 'All tests passed!';
      "

networks:
  app-network:
    driver: bridge