apiVersion: v1
kind: Service
metadata:
  name: dataprep-service
spec:
  selector:
    app: dataprep
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  selector:
    app: model
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: prediction-service
spec:
  selector:
    app: prediction
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000